version: 0.2
phases:
  install:
    commands:
      - npm install --production
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-serverless-giftapp --output-template-file outputSamTemplate.yaml  --capabilities CAPABILITY_NAMED_IAM
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
